---
- name: "Install Apache2"
  apt: name=apache2 state=present

- name: "Add Virtualhost config file"
  become: yes
  become_user: root
  copy: src=files/vhost.conf dest=/etc/apache2/sites-enabled/000-default.conf

- name: "Add Ubuntu as a owner of /var/www/html"
  file:
    path: /var/www/html
    owner: ubuntu
    group: www-data
    mode: 0755
  become: yes
  become_user: root

- name: "Restart Apache2"
  become: yes
  become_user: root
  service: name=apache2 state=reloaded