# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.ssh.forward_agent = false
  config.vm.box_check_update = false

  config.vm.synced_folder "../ansible", "/ansible"
  config.vm.synced_folder "../shared/www/", "/var/www/html/", type: "virtualbox", create: true

  config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.name = "Performance - Ubuntu 16.04"
      vb.memory = "1024"
  end

  config.vm.define "web", primary: true do |web|
    web.vm.network :private_network, ip: "192.168.22.22"
    web.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
    web.vm.network :forwarded_port, guest: 443, host: 8081, auto_correct: true
    web.vm.hostname = "ubuntu.dev"

    web.vm.provision :shell, path: "provision.sh"
  end

end
