---
- name: Install PHP 7.0
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  become: yes
  become_user: root
  with_items:
    - php7.0
    - php7.0-fpm
    - php7.0-mysql
    - libapache2-mod-php
    - php7.0-curl
    - php7.0-json
    - php7.0-cgi
