---
- name: "Add PHP7.1 repository"
  apt_repository:
    repo: "ppa:ondrej/php"

- name: "Update and upgrade apt packages"
  become: true
  apt:
    update_cache: yes

- name: "Install PHP 7.1"
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  become: yes
  become_user: root
  with_items:
    - php7.1
    - php7.1-fpm
    - php7.1-mysql
    - php7.1-curl
    - php7.1-json
    - php7.1-cgi
    - php7.1-xml
    - php-redis
    - libapache2-mod-php7.1

- name: "Install composer"
  become: yes
  become_user: root
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
