---
- name: "Install PHP 7.0"
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  become: yes
  become_user: root
  with_items:
    - php7.0
    - php7.0-fpm
    - php7.0-mysql
    - php7.0-curl
    - php7.0-json
    - php7.0-cgi
    - php7.0-xml
    - php-redis
    - libapache2-mod-php7.0

- name: "Install composer"
  become: yes
  become_user: root
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
