---
#
# Development playbook to group development config
# For Vagrant environment, for example.
#

- name: "-------------------- Start Development playbook -----------------------"
  hosts: web_server
  become: true
  gather_facts: no
  pre_tasks:
    - name: "Install python2"
      raw: sudo apt-get -y install python python-simplejson
  become_user: root
  user: ubuntu
  roles:
    - common
    - apache
    - php
    - mysql
    - redis