---
#
# Redis playbook for a distributed server of Redis
#

- name: "------------------------ Start redis playbook -------------------------"
  hosts: redis_server
  become: true
  gather_facts: no
  pre_tasks:
    - name: "Install python2"
      raw: sudo apt-get -y install python python-simplejson
  tasks:
    - common
    - php
    - redis