---
- name: "------------------------ Start redis playbook -------------------------"
  hosts: redis
  become: true
  gather_facts: no
  pre_tasks:
    - name: "Install python2"
      raw: sudo apt-get -y install python python-simplejson
  tasks:
    - php
    - redis